= Contributing

We welcome your contributions! There are multiple ways to contribute.

== Issues

For bugs or enhancement requests, please file a GitHub issue unless it's security related. When filing a bug remember that the better written the bug is, the more likely it is to be fixed. If you think you've found a security vulnerability, do not raise a GitHub issue and follow the instructions on our xref:./SECURITY.adoc[Security Policy].

== Contributing Code

We welcome your code contributions. To get started, you will need to sign the
https://oca.opensource.oracle.com/[Oracle Contributor Agreement] (OCA).

For pull requests to be accepted, the bottom of your commit message must have
the following line using the name and e-mail address you used for the OCA.

[source,bash]
----
Signed-off-by: Your Name <you@example.org>
----

This can be automatically added to pull requests by committing with:

[source,bash]
----
git commit --signoff
----

Only pull requests from committers that can be verified as having
signed the OCA can be accepted.

=== Pull request process

. Fork this repository
. Create a branch in your fork to implement the changes. We recommend using
the issue number as part of your branch name, e.g. `1234-fixes`
. Ensure that any documentation is updated with the changes that are required
by your fix.
. Ensure that any samples are updated if the base image has been changed.
. Submit the pull request. _Do not leave the pull request blank_. Explain exactly
what your changes are meant to do and provide simple steps on how to validate
your changes. Ensure that you reference the issue you created as well.
. We will assign the pull request to 2-3 people for review before it is merged.

== Code of Conduct

Follow the https://en.wikipedia.org/wiki/Golden_Rule[Golden Rule]. If you'd like more specific guidelines see the https://www.contributor-covenant.org/version/1/4/code-of-conduct/[Contributor Covenant Code of Conduct]
