///////////////////////////////////////////////////////////////////////////////
    Copyright (c) 2013, 2026, Oracle and/or its affiliates.

    Licensed under the Universal Permissive License v 1.0 as shown at
    https://oss.oracle.com/licenses/upl.
///////////////////////////////////////////////////////////////////////////////

= Change History
:description: Oracle Coherence Hibernate Website
:keywords: coherence, hibernate, java, documentation

// DO NOT remove this header - it might look like a duplicate of the header above, but
// both they serve a purpose, and the docs will look wrong if it is removed.

== Change History

The following sections outline Oracle Coherence Hibernate Integration changes in
reverse chronological order.

=== Version 4.0.0 (September 23, 2026)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v4.0.0

* Require Java 17 and validate the project on Java 17, 21, and 25.
* Upgrade the current integration baseline to Hibernate ORM `7.4.x` and Jakarta Persistence `3.2`.
* Publish `coherence-hibernate-cache-7` as the sole 4.x second-level cache adapter.
* Restore support for `hibernate.cache.keys_factory`. Earlier 4.0 snapshots ignored this setting and always used
  the default factory. When upgrading from those snapshots with `simple` or a custom factory that changes the key
  format, stop users of the affected cache regions and evict those regions before restarting, or use new isolated
  regions. Do not mix members using different key formats in the same regions.
* Keep Hibernate `5.6.x` and `6.x` support on the Coherence Hibernate `3.x` maintenance line.
* Remove the obsolete `coherence14_1_1` Maven profile and Coherence 14.1.1 compatibility code. Create sessions using
  `SessionConfiguration`; Coherence 14.1.1 is not supported by the 4.x release.
* Compatibility-test Hibernate `7.4.1.Final`, `7.4.5.Final`, and `7.4.9.Final` with Coherence CE `15.1.1-0-5` and
  `26.07` on the Java 17 bytecode baseline, in addition to the complete default-version reactor on Java 17, 21, and 25.

=== Version 3.0.3 (October 6, 2024)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v3.0.3

=== Version 3.0.2 (March 18, 2024)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v3.0.2

=== Version 3.0.1 (January 27, 2024)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v3.0.1

=== Version 3.0.0 (July 4, 2023)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v3.0.0

=== Version 2.3.3 (July 2, 2023)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.3.3

=== Version 2.3.2 (January 26, 2023)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.3.2

=== Version 2.3.1 (November 3, 2022)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.3.1

=== Version 2.3.0 (August 25, 2022)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.3.0

=== Version 2.2.0 (August, 2022)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.2.0

=== Version 2.1.1 (Jan, 2022)

https://github.com/coherence-community/coherence-hibernate/releases/tag/v2.1.1

=== Version 2.1.0-M1 (Nov 2021)

==== Global and Cross-Module Changes

* Add sample application
* Require `Java 11` to build the project. When solely using, Java 8 is still supported

==== coherence-hibernate-second-level-cache

* Add support for configurable CacheKeysFactories in Hibernate `5.2.x`
* Add support for Hibernate `5.3.x`, `5.4.x`, `5.5.x`, `5.6.x`

==== coherence-hibernate-site

* Migrate to new website format
* Publish JavaDoc

=== Version 2.0.0 @ 2020-11-25 15:30

==== Global and Cross-Module Changes

* Change licensing from the COMMON DEVELOPMENT AND DISTRIBUTION LICENSE (CDDL)
to The Universal Permissive License (UPL)
* Updating of dependencies.
* Merge functional tests into the respective versions

==== coherence-hibernate-cache-store

* Update dependencies

==== coherence-hibernate-second-level-cache

* Add support for Hibernate `4.3.x`, `5.0.x`, `5.1.x`, `5.2.x`
* Add additional modules for the various Hibernate versions

==== coherence-hibernate-site

* Polishing and updating for `2.0.0`
* Update site code

=== Version 1.0.0 @ 2013-09-12 15:30

==== Source and Documentation Contributors

* Randy Stafford

==== Global and Cross-Module Changes

* Initial release.

==== coherence-hibernate-cache-store

* Initial release.

==== coherence-hibernate-cache-store-tests

* Initial release.

==== coherence-hibernate-second-level-cache

* Initial release.

==== coherence-hibernate-second-level-cache-tests

* Initial release.

==== coherence-hibernate-site

* Initial release.
