debug: false
server:
  port: 8081
logging:
  level:
    com.oracle.coherence: DEBUG
spring:
  datasource:
    url: jdbc:hsqldb:hsql://localhost:9001/maindb
    username: coherence
    password: rocks
