# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Coherence Hibernate
on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2.0.0
      with:
        distribution: 'adopt'
        java-version: '8'
    - name: Build - Hibernate 5.4.x
      run: mvn clean install -B -Powasp -Phibernate54
    - name: Build - Hibernate 5.5.x
      run: mvn clean install -B -Powasp -Phibernate55
    - name: Build - Hibernate 5.6.x
      run: mvn clean install -B -Powasp -Phibernate56
    - name: Build + deploy with Maven (Website + Snapshots)
      run: mvn clean deploy -B -Powasp --settings .mvn/settings.xml
      env:
        MAVEN_GITHUB_TOKEN: "${{secrets.MAVEN_GITHUB}}"
        MAVEN_SONATYPE_USERNAME: "${{secrets.MAVEN_SONATYPE_USERNAME}}"
        MAVEN_SONATYPE_TOKEN: "${{secrets.MAVEN_SONATYPE_TOKEN}}"
