name: Schedule Nightly Builds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
jobs:
  schedule:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, 2.3.x]
    steps:
      - uses: benc-uk/workflow-dispatch@d004979be141727c7a17c28f603e2facc40d0855 # v1.3.3
        with:
          workflow: CI Coherence Hibernate
          ref: ${{ matrix.branch }}
